#Quadratic Gosper
iterations = 2
distance = 10
line_width = 3
axiom = "-YF"
rules = ["X:XFX-YF-YF+FX+FX-YF-YFFX+YF+FXFXYF-FX+YF+FXFX+YF-FXYF-YF-FX+FX+YFYF-",
    "Y:+FXFX-YF-YF+FX+FXYF+FX-YFYF-FX-YF+FXYFYF-FX-YFFX+FX+YF-YF-FX+FX+YFY"]
angle = 90.0
