
[main]
width = 1920
height = 1080
type = "LSYSTEM" # MANDELBROT, JULIA, NEWTON, LAPUNOV, LSYSTEM
is_video = false
is_slides = false
out_path = "out"
thread_size = 8
frames_copy = 10 # put frame copies in video
fps = 10
bg_color = [0, 0, 0]

[mandelbrot]
dim = 2
center = [0.0, 0.0]
center_to = [0.0, 0.0] # for video or slides
center_step = [0.0, 0.0] # for video or slides
range = [3.0, 2.5]
range_to = [0.0, 0.0] # for video or slides
range_step = [0.0, 0.0] # for video or slides
max_iterations = 312
is_cloud = false
cloud_step = 1
#script = "configs/script/test.lua" # if use script that ignore dim

[lapunov]
# thish mode work in range [0, 4]
# dim not support
center = [2.0, 2.0]
center_to = [0.0, 0.0] # for video or slides
center_step = [0.0, 0.0] # for video or slides
range = [3.0, 3.0]
range_to = [0.0, 0.0] # for video or slides
range_step = [0.0, 0.0] # for video or slides
max_iterations = 1000
pattern = "AABABBA"
xn = 0.5
rotate_angle = 0.0
rotate_angle_to = 0.0
rotate_angle_step = 0.0

[julia]
dim = 3
range = [2.0, 2.0]
range_to = [0.0, 0.0] # for video or slides
range_step = [0.0, 0.0] # for video or slides
center = [0.28, 0.0113]
center_to = [0.0, 0.0] # for video or slides
center_step = [0.0, 0.0] # for video or slides
max_iterations = 512
c = [0.285, 1.0] #optional, if c is null, it calculate by r
r = 0.7885
a = 0.0 # need to calc a
a_to = 0.0 # for video or slides
a_step = 0.0 # for video or slides
is_cloud = true
cloud_step = 1
#script = "configs/script/test.lua" # if use script that ignore dim

[newton]
# dim not support
center = [0.0, 0.0]
center_to = [0.0, 0.0] # for video or slides
center_step = [0.0, 0.0] # for video or slides
range = [2.0, 2.0]
range_to = [0.0, 0.0] # for video or slides
range_step = [0.0, 0.0] # for video or slides
max_iterations = 21312
coefs = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0] # polynom 4 dim

[lsystem]
rule = "configs/lsystem/1.toml"

[color]
sheme = "configs/colors/rainbowCircle.toml"
