colors = [[[255, 233, 199],[0, 0, 1],[57, 80, 54],[163, 124,  25],[255, 255, 255]]]

count_step_x = 100                                                        # count of grad steps X
count_step_y = 10                                                         # count of grad steps Y
step_size_x = 1                                                           # size steps for every colo X
step_size_y = 1                                                           # size steps for every colo Y
